window.addEventListener('error',e=>{const a=document.getElementById('app');if(a&&!a.innerHTML)a.innerHTML='<p style="padding:24px;font:16px system-ui">Error: '+e.message+'</p>'});
const S=(k)=>{try{return localStorage.getItem(k)}catch(e){return null}};
let lang=S('l')||((navigator.language||'').startsWith('fr')?'fr':'en');const i=lang==='fr'?1:0;
const L=x=>Array.isArray(x)?x[i]:x;
const U={
nav:[["Home","Accueil"],["Projects","Projets"],["About","À propos"],["Contact","Contact"]],
st:["Seeking a 6-month final-year internship (PFE) · from February 2027","À la recherche d'un stage PFE de 6 mois · dès février 2027"],cv:["Download my CV","Télécharger mon CV"],proj:["See the project","Voir le projet"],
role:["Final-year engineering student in Data Engineering & AI, ENSA Agadir","Étudiante ingénieure en dernière année en Data Engineering & IA, ENSA Agadir"],
intro:["Interested in Data Engineering and AI. Hands-on skills in ETL pipelines, data warehousing, machine learning, AI agents / LLMs and full-stack development. Motivated by turning raw data into actionable insights.","Intéressée par le Data Engineering et l'IA. Compétences pratiques en pipelines ETL, entreposage de données, Machine Learning, agents IA / LLM et développement Full-Stack. Motivée par la transformation de données brutes en insights actionnables."],
see:["See my projects","Voir mes projets"],touch:["Get in touch","Me contacter"],feat:["Featured projects","Projets à la une"],
all:["All","Tous"],ai:["AI & Agents","IA & Agents"],de:["Data Engineering","Data Engineering"],ml:["Machine Learning","Machine Learning"],fs:["Full-Stack","Full-Stack"],
dc:["Guided projects (DataCamp)","Projets guidés (DataCamp)"],back:["← All projects","← Tous les projets"],
shot:["Screenshots","Captures d'écran"],code:["Code examples","Exemples de code"],todo:["To fill: ","À compléter : "],
edu:["Education","Formation"],exp:["Experience","Expérience"],cert:["Certifications","Certifications"],lg:["Languages","Langues"],sk:["Skills","Compétences"],
mail:["Email","E-mail"],pt:["Based in Agadir, Morocco. Looking for an opportunity in data engineering, AI or full-stack development.","Basée à Agadir, Maroc. À la recherche d'une opportunité en data engineering, IA ou développement full-stack."]};
const P=[
{id:"agent",g:["ai","fs"],k:["Internship (PFA) · Jul-Sep 2026 · Team of 2","Stage (PFA) · Juil-Sept 2026 · Équipe de 2"],t:["AI Agent for ERP","Agent IA pour ERP"],
s:["A chatbot inside an ERP that answers business questions in plain language, using tested database tools first and a guarded SQL fallback.","Un chatbot intégré à un ERP qui répond aux questions métier en langage naturel, avec d'abord des outils de base de données testés, puis un repli SQL protégé."],
st:"Python, FastAPI, SQLAlchemy, PostgreSQL, React, Recharts, Ollama, Groq, sentence-transformers",
b:[["ERP users had to open several reports and cross-check numbers to answer simple questions.","Les utilisateurs de l'ERP devaient ouvrir plusieurs rapports et recouper les chiffres pour répondre à des questions simples."],
["Path 1: about 21 predefined tools, each tied to a tested PostgreSQL view or function. Sentence embeddings pick the right tool even if the question doesn't match its name.","Voie 1 : environ 21 outils prédéfinis, chacun lié à une vue ou fonction PostgreSQL testée. Des embeddings de phrases choisissent le bon outil même si la question ne reprend pas son nom."],
["Path 2: when no tool fits, the model writes one SELECT query. It is validated before running: SELECT only, approved views, no dangerous keywords, forced LIMIT, read-only under a restricted role.","Voie 2 : quand aucun outil ne convient, le modèle écrit une requête SELECT, validée avant exécution : SELECT seul, vues autorisées, pas de mots-clés dangereux, LIMIT imposé, lecture seule sous un rôle restreint."],
["Isolated reporting schema with least-privilege roles. The agent and the dashboards share one backend through service-account authentication.","Schéma de reporting isolé avec rôles à moindre privilège. L'agent et les dashboards partagent un backend via une authentification par compte de service."],
["Tested local (Ollama) and cloud (Groq) models, and fixed hallucinations, redundant tool calls and latency across 3B vs 7B+ model sizes.","Modèles locaux (Ollama) et cloud (Groq) testés ; correction des hallucinations, des appels d'outils redondants et de la latence selon la taille du modèle (3B vs 7B+)."],
["Four React dashboards (stock, purchases, suppliers, quotes) with date filters shared by every chart, plus the chat widget inside the ERP.","Quatre dashboards React (stock, achats, fournisseurs, devis) avec des filtres de dates communs à tous les graphiques, plus le chatbot intégré à l'ERP."]],
nt:["Interface with test data.","Interface avec données de test."],
im:[["ag1.jpg",["Chatbot: all refunds for a month, with the total","Chatbot : tous les remboursements d'un mois, avec le total"]],["ag2.jpg",["The agent spots a misspelled client name and offers to retry","L'agent repère un nom de client mal orthographié et propose de réessayer"]],["ag3.jpg",["Business question: products with an abnormal return rate","Question métier : produits avec un taux de retour anormal"]],["ag4.jpg",["Answer with a \"View SQL\" link showing the query behind it","Réponse avec un lien « Voir le SQL » qui montre la requête utilisée"]],["ag9.jpg",["Dashboard home: KPIs and sales evolution","Accueil : KPIs et évolution des ventes"]],["ag5.jpg",["Stock report with date filter","Rapport de stock avec filtre de dates"]],["ag6.jpg",["Sales report: status breakdown and sales map","Rapport des ventes : répartition par statut et carte des ventes"]],["ag7.jpg",["Customer report: top customers and lifetime value","Rapport clients : meilleurs clients et valeur vie client"]],["ag8.jpg",["Payments report","Rapport des paiements"]],["ag10.jpg",["Login page","Page de connexion"]]]},
{id:"irrigation",g:["ml","ai","fs"],k:["Academic project · 2025-2026 · Team of 5","Projet académique · 2025-2026 · Équipe de 5"],t:["Smart Irrigation System","Système d'irrigation intelligent"],
s:["An AI assistant that predicts when crops need water, diagnoses plant diseases from photos, and collects farmer feedback.","Un assistant IA qui prédit quand les cultures ont besoin d'eau, diagnostique les maladies à partir de photos et collecte les retours des agriculteurs."],
st:"Python, XGBoost, scikit-learn, Keras, MLflow, DagsHub, DVC, FastAPI, React, TypeScript",
ln:[["GitHub","https://github.com/Saadiaboussiar/Smart-Irrigation-Project"],["DagsHub","https://dagshub.com/Saadiaboussiar/Smart-Irrigation-Project"]],
b:[["Predicts water needs from soil moisture, temperature, rainfall, wind and growth stage, with irrigation volumes from the FAO Blaney-Criddle method.","Prédit les besoins en eau à partir de l'humidité du sol, de la température, des précipitations, du vent et du stade de croissance, avec des volumes d'irrigation selon la méthode FAO Blaney-Criddle."],
["Simulation: 5 crops and 15 zones driven by real Agadir weather (Open-Meteo), updated every 15 minutes.","Simulation : 5 cultures et 15 zones alimentées par la météo réelle d'Agadir (Open-Meteo), mises à jour toutes les 15 minutes."],
["5 models compared in MLflow on DagsHub. XGBoost went to production (~99.9% accuracy, on simulated data, so it needs validation on real data). SVM 94.3%, MLP 90.5%, Random Forest ~92%, Logistic Regression 73.8%.","5 modèles comparés avec MLflow sur DagsHub. XGBoost est passé en production (~99,9 % de précision, sur données simulées, donc à valider sur données réelles). SVM 94,3 %, MLP 90,5 %, Random Forest ~92 %, Régression logistique 73,8 %."],
["Vision: EfficientNetB0 on 12 plant diseases. A working pipeline, but with low accuracy so far.","Vision : EfficientNetB0 sur 12 maladies de plantes. Un pipeline fonctionnel, mais encore peu précis."],
["Feedback loop: farmers flag wrong predictions, saved for future retraining.","Boucle de feedback : les agriculteurs signalent les prédictions erronées, enregistrées pour un futur réentraînement."],
["My part: the MLP (feature selection, SMOTE on training data only, decision threshold 0.40 that cut missed thirsty plants from 76 to 45) and the whole React + TypeScript mobile app.","Ma part : le MLP (sélection de variables, SMOTE sur l'entraînement uniquement, seuil de décision à 0,40 qui a réduit les plantes assoiffées non détectées de 76 à 45) et toute l'application mobile React + TypeScript."]],
nt:["Screenshots are a live snapshot from the simulator, so numbers change from one screen to the next.","Les captures sont un instantané du simulateur : les chiffres changent d'un écran à l'autre."],
im:[["ir1.jpg",["Live overview of the zones being analysed","Vue en direct des zones analysées"]],["ir2.jpg",["Status and moisture for each crop","État et humidité de chaque culture"]],["ir3.jpg",["Share of zones needing water; moisture vs temperature per crop","Part des zones à arroser ; humidité vs température par culture"]],["ir4.jpg",["Garden map: each zone by status","Carte du jardin : chaque zone selon son statut"]],["ir5.jpg",["Plant scanner for the disease model","Scanner de plantes pour le modèle de diagnostic"]],["ir6.jpg",["One entry per crop, with history","Une entrée par culture, avec son historique"]],["ir7.jpg",["Per-zone readings and predictions for one crop","Mesures et prédictions par zone pour une culture"]],["ir8.jpg",["Water-need alerts, with a button to flag a wrong prediction","Alertes de besoin en eau, avec un bouton pour signaler une prédiction erronée"]],["ir9.jpg",["Language and irrigation preferences","Langue et préférences d'irrigation"]],["mlp-cm.jpg",["MLP confusion matrix (threshold 0.40)","Matrice de confusion du MLP (seuil 0,40)"]],["mlp-roc.jpg",["MLP ROC curve (AUC 0.977)","Courbe ROC du MLP (AUC 0,977)"]],["registry.jpg",["Model registry on DagsHub (MLflow)","Registre des modèles sur DagsHub (MLflow)"]]]},
{id:"dweb",g:["fs"],k:["Internship · Summer 2025 · Individual","Stage · Été 2025 · Individuel"],t:["DwebIntervention: digital intervention vouchers","DwebIntervention : bons d'intervention numériques"],
s:["A full-stack web app that replaced paper intervention reports: technicians fill them in on site, admins validate them.","Une application web full-stack qui a remplacé les fiches d'intervention papier : les techniciens les remplissent sur site, les administrateurs les valident."],
st:"Spring Boot, Spring Security (JWT), JPA/Hibernate, PostgreSQL, Flyway, React, TypeScript, Redux, Material-UI, Chart.js, Docker Compose",
ln:[["Backend","https://github.com/Saadiaboussiar/dweb-App-Backend"],["Frontend","https://github.com/Saadiaboussiar/dweb-App-Frontend"]],
b:[["Problem: paper forms were slow, easy to lose, impossible to follow in real time, and unusable for analysis.","Problème : les fiches papier étaient lentes, faciles à perdre, impossibles à suivre en temps réel et inexploitables pour l'analyse."],
["Technicians: create an intervention, upload a photo of the signed voucher, get validation or rejection notifications, correct and resubmit, and follow a personal dashboard.","Techniciens : créer une intervention, téléverser la photo du bon signé, recevoir les notifications de validation ou de rejet, corriger et renvoyer, et suivre un tableau de bord personnel."],
["Admins: colour-coded queue of new and edited interventions, side-by-side comparison with the voucher, validate or reject with a reason (validation triggers an automatic bonus), manage technicians and clients, view performance and profitability dashboards.","Administrateurs : file d'attente avec code couleur, comparaison côte à côte avec le bon, validation ou rejet avec justification (la validation attribue automatiquement une prime), gestion des techniciens et des clients, dashboards de performance et de rentabilité."],
["Security: JWT, BCrypt-hashed passwords, forced password change at first login, 6-digit reset code valid 15 minutes, generic error messages against account enumeration.","Sécurité : JWT, mots de passe hachés avec BCrypt, changement obligatoire du mot de passe à la première connexion, code de réinitialisation à 6 chiffres valable 15 minutes, messages d'erreur génériques contre l'énumération de comptes."],
["Architecture: separate React frontend and layered Spring Boot REST API, Flyway database migrations, Docker Compose for PostgreSQL and pgAdmin. Built alone in two months, remotely.","Architecture : frontend React séparé et API REST Spring Boot en couches, migrations Flyway, Docker Compose pour PostgreSQL et pgAdmin. Réalisé seule en deux mois, à distance."]],
nt:["Interface with sample data.","Interface avec données d'exemple."],
im:[["dw1.jpg",["Technician: new intervention form with voucher photo","Technicien : formulaire d'intervention avec photo du bon"]],["dw2.jpg",["Technician: personal dashboard","Technicien : tableau de bord personnel"]],["dw5.jpg",["Admin: queue of new and edited interventions","Admin : file des interventions nouvelles et modifiées"]],["dw6.jpg",["Admin: validating an intervention next to the voucher photo","Admin : validation d'une intervention avec la photo du bon"]],["dw3.jpg",["Admin: global performance dashboard","Admin : tableau de bord de performance globale"]],["dw4.jpg",["Application architecture","Architecture de l'application"]],["dw7.jpg",["Authentication sequence diagram (JWT)","Diagramme de séquence de l'authentification (JWT)"]]]},
{id:"warehouse",g:["de"],k:["Academic project · Team","Projet académique · Équipe"],t:["Logistics Data Warehouse & Fleet Analytics","Entrepôt de données logistique & analyse de flotte"],
s:["An end-to-end ETL and BI pipeline that turns raw trucking CSV files into a MySQL star schema and Power BI dashboards.","Un pipeline ETL et BI complet qui transforme des fichiers CSV bruts de transport routier en schéma en étoile MySQL et tableaux de bord Power BI."],
st:"Pentaho PDI, MySQL, Power BI",
ln:[["GitHub","https://github.com/Saadiaboussiar/etl-dwh-bi-project"]],
b:[["Data: the synthetic Logistics Operations Database (Kaggle, 2022-2024), a fictional trucking company with 120 trucks.","Données : la base synthétique Logistics Operations Database (Kaggle, 2022-2024), une entreprise de transport fictive de 120 camions."],
["Staging: one Pentaho transformation per source file, with cleaning (trimming, duplicates, nulls, missing drivers, calculated fields).","Staging : une transformation Pentaho par fichier source, avec nettoyage (espaces, doublons, valeurs nulles, conducteurs manquants, champs calculés)."],
["Dimensions (customers, trucks, trailers, drivers, facilities, routes, generated date) and facts (trips, safety incidents, maintenance, fuel purchases), loaded into MySQL.","Dimensions (clients, camions, remorques, conducteurs, sites, routes, date générée) et faits (trajets, incidents de sécurité, maintenance, achats de carburant), chargés dans MySQL."],
["Dashboards: utilisation rate 0.76, 2.02M active hours, 115.03M miles; fleet time split 75.9% active, 21.4% idle, 2.7% downtime.","Tableaux de bord : taux d'utilisation 0,76, 2,02 M d'heures actives, 115,03 M de miles ; temps de flotte réparti en 75,9 % d'activité, 21,4 % d'inactivité, 2,7 % d'arrêt."],
["We worked as a team and split the tables and KPIs among us.","Nous avons travaillé en équipe et nous sommes réparti les tables et les KPI."]],
im:[["dwh1.jpg",["Fleet utilisation dashboard (Power BI)","Tableau de bord d'utilisation de la flotte (Power BI)"]],["pe1.jpg",["Staging: delivery events transformation (Pentaho)","Staging : transformation des événements de livraison (Pentaho)"]],["pe2.jpg",["Pentaho Spoon: staging transformations and execution log","Pentaho Spoon : transformations de staging et journal d'exécution"]],["pe3.jpg",["Date dimension generated in Pentaho","Dimension date générée dans Pentaho"]],["pe4.jpg",["Trip fact table transformation","Transformation de la table de faits des trajets"]],["pe5.jpg",["MySQL: trip fact table and related dimensions","MySQL : table de faits des trajets et dimensions liées"]]]},
{id:"clustering",g:["ml"],k:["Academic project · Individual","Projet académique · Individuel"],t:["Mall Customer Segmentation","Segmentation de clients d'un centre commercial"],
s:["Groups 200 mall customers into four marketing personas with three clustering methods, then assigns new customers to a persona.","Regroupe 200 clients d'un centre commercial en quatre personas marketing avec trois méthodes de clustering, puis affecte les nouveaux clients à un persona."],
st:"Python, Pandas, Scikit-learn, SciPy, Plotly, Matplotlib, Seaborn",
ln:[["GitHub","https://github.com/Saadiaboussiar/mall-customer-segmentation"]],
b:[["Exploration by age, gender and income: spending drops after age 40, and income and spending are almost uncorrelated (0.01), which is why clustering is needed.","Exploration par âge, genre et revenu : la dépense baisse après 40 ans, et revenu et dépense sont presque non corrélés (0,01), d'où le besoin de clustering."],
["Four standardised variables (gender, age, income, spending score). k = 4 chosen with the elbow method and silhouette scores.","Quatre variables standardisées (genre, âge, revenu, score de dépense). k = 4 choisi avec la méthode du coude et les scores de silhouette."],
["K-Means++ (silhouette 0.29), hierarchical Ward clustering (0.26, used for the final personas), DBSCAN (16 outliers, 8% of customers).","K-Means++ (silhouette 0,29), classification hiérarchique de Ward (0,26, utilisée pour les personas finaux), DBSCAN (16 valeurs aberrantes, 8 % des clients)."],
["Personas: VIP Spenders, Target Growth, Silent Giants, Conservative Core, each with a marketing action.","Personas : VIP Spenders, Target Growth, Silent Giants, Conservative Core, chacun avec une action marketing."],
["A KNN classifier reproduced the persona for 95% of a 40-customer test set, used as a stability check and to assign new customers.","Un classifieur KNN a retrouvé le persona pour 95 % d'un jeu de test de 40 clients, utilisé comme contrôle de stabilité et pour affecter les nouveaux clients."]],
im:[["mall1.jpg",["Final personas (income vs spending)","Personas finaux (revenu vs dépense)"]],["mall2.jpg",["Silhouette score by number of clusters","Score de silhouette selon le nombre de clusters"]],["mall3.jpg",["Dendrogram (Ward linkage)","Dendrogramme (liaison de Ward)"]]]},
{id:"parking",g:["ml","ai"],k:["Academic project · 2026 · Individual","Projet académique · 2026 · Individuel"],t:["Parking Spot Detection: OpenCV vs CNN","Détection de places de parking : OpenCV vs CNN"],
s:["Two systems that detect free and occupied spaces in an aerial photo: classical image processing and a convolutional neural network.","Deux systèmes qui détectent les places libres et occupées sur une photo aérienne : traitement d'image classique et réseau de neurones convolutif."],
st:"Python, OpenCV, TensorFlow/Keras, NumPy, scikit-learn, Matplotlib",
ln:[["GitHub","https://github.com/Saadiaboussiar/Parking-spot-detection"]],
b:[["Classical method: 33 spaces marked by hand, then grayscale, Gaussian blur and adaptive thresholding. A space is free if it has fewer than 500 white pixels. No training data needed, but sensitive to lighting.","Méthode classique : 33 places marquées à la main, puis niveaux de gris, flou gaussien et binarisation adaptative. Une place est libre si elle a moins de 500 pixels blancs. Aucune donnée d'entraînement, mais sensible à l'éclairage."],
["CNN: trained on 813 labelled space images (192 free, 621 occupied) at 64×64, 80/20 split, 15 epochs. 98.2% accuracy on the 163-image test set.","CNN : entraîné sur 813 images de places étiquetées (192 libres, 621 occupées) en 64×64, répartition 80/20, 15 époques. 98,2 % de précision sur le jeu de test de 163 images."],
["On the test photo, the classical method found 2 free spaces and the CNN found 3, with a confidence score for each space.","Sur la photo de test, la méthode classique a trouvé 2 places libres et le CNN en a trouvé 3, avec un score de confiance par place."],
["Next: a larger and more varied dataset, transfer learning, and tests on other lots and lighting.","Suite : un jeu de données plus large et plus varié, du transfer learning, et des tests sur d'autres parkings et éclairages."]],
im:[["pk1.jpg",["Original aerial photo","Photo aérienne d'origine"]],["pk2.jpg",["Classical method: 2 free, 31 occupied","Méthode classique : 2 libres, 31 occupées"]],["pk3.jpg",["CNN: 3 free, 30 occupied, with confidence","CNN : 3 libres, 30 occupées, avec confiance"]],["pk4.jpg",["CNN learning curves","Courbes d'apprentissage du CNN"]]]},
{id:"airport",g:["fs"],k:["Academic project (Oracle administration module) · 2025-2026 · Team of 4","Projet académique (module Administration Oracle) · 2025-2026 · Équipe de 4"],t:["Airport Management System","Système de gestion aéroportuaire"],
s:["A database-centred application for airport operations: the business rules live in Oracle PL/SQL, with a FastAPI and React app on top.","Une application centrée sur la base de données pour les opérations aéroportuaires : les règles métier sont en PL/SQL Oracle, avec une application FastAPI et React par-dessus."],
st:"Oracle Database, PL/SQL, FastAPI, SQLAlchemy, React, TypeScript, Axios",
ln:[["GitHub","https://github.com/amineaith3/AE-Project"]],
b:[["Database layer: tables, views and sequences, plus PL/SQL procedures, functions and triggers that enforce the business rules directly in the database.","Couche base de données : tables, vues et séquences, plus des procédures, fonctions et triggers PL/SQL qui appliquent les règles métier directement dans la base."],
["Security: roles and privileges control who can do what, based on the logged-in admin's privileges.","Sécurité : des rôles et privilèges contrôlent qui peut faire quoi, selon les privilèges de l'administrateur connecté."],
["Backend: FastAPI talking to Oracle through SQLAlchemy, tested with Swagger UI.","Backend : FastAPI communiquant avec Oracle via SQLAlchemy, testé avec Swagger UI."],
["Frontend: React and TypeScript with CRUD screens for flights, passengers, staff and other resources.","Frontend : React et TypeScript avec des écrans CRUD pour les vols, passagers, personnel et autres ressources."],["My part: I wrote the triggers, functions and procedures for the aircraft table.","Ma part : j'ai écrit les triggers, fonctions et procédures de la table des avions."]],
im:[["ae2.jpg",["Admin interface: passengers management","Interface d'administration : gestion des passagers"]],["ae1.jpg",["Three-tier architecture: React, FastAPI, Oracle","Architecture trois-tiers : React, FastAPI, Oracle"]],["ae3.jpg",["Sidebar with the five modules","Barre latérale avec les 5 modules"]],["ae4.jpg",["Admin login page","Page de connexion de l'administration"]]]}];
const DC=[["Los Angeles Crime Analysis","Analyse de la criminalité à Los Angeles","Crime trends and patterns in Los Angeles.","Tendances et schémas de la criminalité à Los Angeles."],
["Netflix Movies Investigation","Enquête sur les films Netflix","Exploratory analysis of Netflix movie and TV show data.","Analyse exploratoire des données de films et séries Netflix."],
["Nobel Prize Visualization","Visualisation des prix Nobel","Nobel Prize laureates over time.","Les lauréats du prix Nobel au fil du temps."],
["NYC School Scores Analysis","Analyse des résultats des écoles de NYC","Academic performance across NYC schools.","Performances scolaires dans les écoles de New York."],
["Students Mental Health Analysis","Analyse de la santé mentale des étudiants","Exploration of student mental health survey data, with Python and SQL.","Exploration de données d'enquête sur la santé mentale des étudiants, avec Python et SQL."]];
const SK=[[["AI & LLMs","IA & LLM"],"Tool calling, prompt engineering, embeddings, Ollama, Groq, NL-to-SQL, Scikit-learn, Keras/TensorFlow, CNN, RAG, OpenCV, MLflow, DVC"],
[["Data","Données"],"ETL, Pentaho, dbt, Apache Airflow, Snowflake, Apache Kafka, Apache Spark, Pandas, NumPy, Power BI, SQL, PL/SQL"],
[["Backend & databases","Backend & bases de données"],"FastAPI, Spring Boot, SQLAlchemy, JWT, PostgreSQL, MySQL, Oracle, MongoDB, Cassandra"],
[["Frontend","Frontend"],"React, TypeScript, Vite, Recharts, Chart.js, Material-UI"],
[["Tools","Outils"],"Git & GitHub, Docker, Jupyter, Postman, VS Code"]];
const card=p=>`<a class=card href="project.html?id=${p.id}">${p.im?`<img src="img/${p.im[0][0]}" alt="" loading=lazy>`:'<div class=ph></div>'}<div class=cb><small>${L(p.k)}</small><h3>${L(p.t)}</h3><p>${L(p.s)}</p></div></a>`;
const tags=s=>`<div class=tg>${s.split(', ').map(x=>`<span>${x}</span>`).join('')}</div>`;
const cv=()=>`<a class=btn href="${i?'CV-Saadia-Boussiar.pdf':'Resume-Saadia-Boussiar.pdf'}" download>${L(U.cv)}</a>`;
const EX=[{d:["Jul – Sep 2026","Juil – Sept 2026"],t:["AI Agent Development Intern for ERP","Stage en développement d'un agent IA pour ERP"],c:"NextAct Solutions",p:"agent",b:[["Developed a conversational AI agent for an ERP: natural-language questions on business data (stock, sales, purchases, quotes) through function calling with Ollama and the Groq API.","Développement d'un agent conversationnel IA pour ERP : interrogation des données métier (stock, ventes, achats, devis) en langage naturel via function calling (Ollama, API Groq)."],["Built a secure PostgreSQL reporting database (views, isolated schema, roles and permissions) and REST APIs with FastAPI and SQLAlchemy.","Base de reporting sécurisée sous PostgreSQL (vues, schéma isolé, rôles et permissions) et API REST avec FastAPI et SQLAlchemy."],["Built React dashboards (KPIs, Recharts, filters, export) and semantic tool selection with embeddings, with a fallback mechanism.","Dashboards React (KPIs, Recharts, filtres, export) et sélection sémantique d'outils par embeddings avec mécanisme de secours."]]},{d:["Jul – Sep 2025","Juil – Sept 2025"],t:["Full-Stack Web Development Intern","Stage en développement web Full Stack"],c:"dweb Technology",p:"dweb",b:[["Developed a full-stack web application for managing the interventions carried out by technicians.","Développement d'une application web full-stack pour la gestion des interventions effectuées par les techniciens."],["Built REST APIs with Spring Boot and optimised PostgreSQL queries.","Création d'API REST avec Spring Boot et optimisation des requêtes PostgreSQL."],["Developed the frontend with React (Vite) and TypeScript.","Développement du frontend avec React (Vite) et TypeScript."]]}];
const R={
home:()=>`<div class="w hero"><span class=pill>${L(U.st)}</span><h1>Saâdia Boussiar</h1><p class=rl>${L(U.role)}</p><p>${L(U.intro)}</p><a class="btn m" href=projects.html>${L(U.see)}</a><a class=btn href=contact.html>${L(U.touch)}</a>${cv()}</div><section><div class=w><h2>${L(U.feat)}</h2><div class=grid>${P.slice(0,3).map(card).join('')}</div></div></section>`,
projects:()=>`<section style="border:0"><div class=w><h2>${L(U.nav[1])}</h2><div class=chips>${['all','ai','de','ml','fs'].map(k=>`<button data-f=${k} class="${k=='all'?'on':''}">${L(U[k])}</button>`).join('')}</div><div class=grid id=gr>${P.map(card).join('')}</div></div></section><section><div class=w><h2>${L(U.dc)}</h2><div class=grid>${DC.map(d=>`<div class=card><div class=cb><h3>${d[i]}</h3><p>${d[i+2]}</p></div></div>`).join('')}</div><p><a class="btn m" href="https://github.com/Saadiaboussiar/datacamp-projects-portfolio">GitHub</a></p></div></section>`,
project:()=>{const p=P.find(x=>x.id==new URLSearchParams(location.search).get('id'))||P[0];document.title=L(p.t)+' | Saâdia Boussiar';
return `<section style="border:0"><div class=w><a href=projects.html>${L(U.back)}</a><h1 style="font-size:clamp(2rem,5vw,3.2rem);margin-top:14px">${L(p.t)}</h1><p class=meta>${L(p.k)}</p>${tags(p.st)}${(p.ln||[]).map(l=>`<a class="btn m" href="${l[1]}">${l[0]}</a>`).join('')}<p class=big style="margin-top:22px">${L(p.s)}</p><ul>${p.b.map(x=>`<li>${L(x)}</li>`).join('')}</ul>${p.td?`<div class=todo>${L(U.todo)}${L(p.td)}</div>`:''}${p.c?`<h2 style="margin-top:36px">${L(U.code)}</h2>${p.c.map(c=>`<p><b>${L(c[0])}</b></p><pre>${c[1]}</pre>`).join('')}`:''}${p.im?`<h2 style="margin-top:36px">${L(U.shot)}</h2>${p.nt?`<p class=meta>${L(p.nt)}</p>`:''}<div class=gal>${p.im.map(m=>`<figure><img src="img/${m[0]}" alt="${L(m[1])}" loading=lazy><figcaption>${L(m[1])}</figcaption></figure>`).join('')}</div>`:''}</div></section>`},
about:()=>`<section style="border:0"><div class=w><h2>${L(U.nav[2])}</h2><p class=big>${L(U.intro)}</p>${cv()}</div></section><section><div class=w><h2>${L(U.exp)}</h2>${EX.map(e=>`<div class=row><b>${L(e.d)}</b><div><h3>${L(e.t)}</h3><p class=meta style="margin:2px 0 8px">${e.c} · Agadir</p><ul>${e.b.map(x=>`<li>${L(x)}</li>`).join('')}</ul><p><a href="project.html?id=${e.p}">${L(U.proj)} →</a></p></div></div>`).join('')}</div></section><section><div class=w><h2>${L(U.edu)}</h2><div class=row><b>2024 – 2027</b><div><h3>${L(["Engineering degree in Data Science, Big Data & AI","Cycle ingénieur en Science des Données, Big Data & IA"])}</h3>ENSA Agadir</div></div><div class=row><b>2022 – 2024</b><div><h3>${L(["Preparatory classes","Classes préparatoires"])}</h3>ENSA Agadir</div></div><div class=row><b>2021 – 2022</b><div><h3>${L(["Baccalaureate, Physical Sciences","Baccalauréat Sciences Physiques"])}</h3>Lycée Al Khawarizmi, Aït Amira</div></div></div></section><section><div class=w><h2>${L(U.sk)}</h2>${SK.map(s=>`<div class=row><b>${L(s[0])}</b><div>${s[1]}</div></div>`).join('')}</div></section><section><div class=w><div class=two><div><h2>${L(U.cert)}</h2><ul><li>AI Career Essentials, ALX</li><li>Data Analyst in Python, DataCamp</li><li>Git & GitHub Fundamentals, DataCamp</li><li>dbt Fundamentals, DataCamp</li><li>Intermediate SQL, DataCamp</li><li>Intro to Snowflake, Snowflake</li><li>Create Local LLMs with Python, Packt</li></ul></div><div><h2>${L(U.lg)}</h2><ul><li>${L(["Arabic, native","Arabe, langue maternelle"])}</li><li>${L(["French, B2","Français, B2"])}</li><li>${L(["English, C1","Anglais, C1"])}</li></ul></div></div></div></section>`,
contact:()=>`<section style="border:0"><div class=w><h2>${L(U.nav[3])}</h2><p class=big>${L(U.pt)}</p><p class=big>${L(U.mail)}: <a href="mailto:boussiarsaadia@gmail.com">boussiarsaadia@gmail.com</a><br><a href="https://www.linkedin.com/in/sa%C3%A2dia-boussiar-960923254/">LinkedIn</a> · <a href="https://github.com/Saadiaboussiar">GitHub</a></p>${cv()}</div></section>`};
const pg=document.body.dataset.p,links=['index','projects','about','contact'];
const on=pg=='project'?'projects':pg=='home'?'index':pg;
document.documentElement.lang=lang;const th=S('t');if(th)document.documentElement.dataset.t=th;
document.getElementById('app').innerHTML=`<header><div class=w><a class=logo href=index.html>Saâdia Boussiar</a><nav>${links.map((l,k)=>`<a href=${l}.html class="${l==on?'on':''}">${L(U.nav[k])}</a>`).join('')}</nav><button id=lg aria-label=Language>${i?'EN':'FR'}</button><button id=tm aria-label=Theme>◐</button></div></header><main>${R[pg]()}</main><footer><div class=w>© 2026 Saâdia Boussiar · Agadir</div></footer>`;
document.getElementById('lg').onclick=()=>{try{localStorage.setItem('l',i?'en':'fr')}catch(e){}location.reload()};
document.getElementById('tm').onclick=()=>{const d=document.documentElement,c=d.dataset.t||(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'),n=c=='dark'?'light':'dark';d.dataset.t=n;try{localStorage.setItem('t',n)}catch(e){}};
document.querySelectorAll('.chips button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.chips button').forEach(x=>x.classList.toggle('on',x==b));document.getElementById('gr').innerHTML=P.filter(p=>b.dataset.f=='all'||p.g.includes(b.dataset.f)).map(card).join('')});
